<?php
	require_once("../includes/config.inc.php");
	
	if(empty($_SESSION['_admin']) == false)
	{
		$f->Redirect('dashboard.php');
	}
	
	$msg = '';
	define("T","`tbl_admin`");
	
	if(isset($_POST['btnSend'])) 
	{
		$flag = 0;
		$your_email_address = $f->XssPOST($_POST['your_email_address']);
				
		$sql="SELECT * FROM ".T." WHERE `your_email_address`='".$your_email_address."' AND `admin_id`=1";
		$res = $db->get($sql,__FILE__,__LINE__);
		if($db->num_rows($res) > 0)
		{
			$flag = 1;
			$row = $db->fetch_array($res);
			$your_name = $f->getHTMLDecode($row['your_name']);
			$your_email_address = $f->getValue($row['your_email_address']);
			$temp_password = $f->RandomNumber(6,false);
			// Updating temp password to database
			$sql = "UPDATE ".T." SET `password`='".$f->makePassword($temp_password)."' WHERE `admin_id`=1";
			$db->get($sql,__FILE__,__LINE__);
			
		}
		
		if($flag == 1)
		{
			$sql_admin = "SELECT * FROM ".T." WHERE `admin_id`=1";
			$res_admin = $db->get($sql_admin);
			$row_admin = $db->fetch_array($res_admin);
			
			$mail_content = "<font style=\"font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;\">"; 
			$mail_content.= "Dear ".$your_name.",<br /><br />";
			$mail_content.= "A temporary password <b>".$temp_password."</b> has been auto generated by the system. Please login with the temporary password and change your password right away.<br /><br />Thanks,<br />".$f->getValue($row_admin['company_name']);
			$mail_content.= "</font>";
			
			//echo $mail_content; exit();
			
			
			// Sending Mail
			$objMail = new PHPMailer();
			$objMail->SetFrom($f->getValue($row_admin['email_from_address']),$f->getHTMLDecode($row_admin['email_from_name']));
			$objMail->Subject = "Forgot Password";
			if($row['smtp']=='Yes'):
				$objMail->IsSMTP();
				$objMail->Host = $f->getValue($row_admin['smtp_hostname']);
				$objMail->SMTPAuth = true;
				if($row['smtp_type'] == "tls" || $row_admin['smtp_type'] == "ssl")
				{
					$objMail->SMTPSecure = $row_admin['smtp_type'];
					$objMail->Port = ($row_admin['smtp_type'] == 'tls') ? 587 : 465;
				}
				$objMail->Username = $f->getValue($row_admin['smtp_username']);
				$objMail->Password = $f->getValue($row_admin['smtp_password']);
			endif;
			$objMail->IsHTML(true);
			//$objMail->Body = $mail_content;
			$objMail->MsgHTML($mail_content);
			$objMail->CharSet = 'UTF-8';
			$objMail->AddAddress($your_email_address, $your_name);
			$objMail->Send();
			$msg = $f->getHtmlMessage('Password has been sent');
			
		}else{
			$msg = $f->getHtmlError('Invalid Email Address Provided');
		}
	}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<?php include('admin-css-js.php');?>
<script type="text/javascript">
$(document).ready(function() {
	$('#frmForgotPassword').validate();
});
</script>
</head>
<body>
<div id="loginbox">	
	<div class="login_logo"><img src="<?php echo MAIN_WEBSITE_URL;?>/<?php echo $WEBSITE_LOGO;?>" alt="" /></div>
	<p class="normal_text">Enter your e-mail address below and we will send you instructions how to recover a password.</p>
	<form action="<?php echo CP;?>" method="post" id="frmForgotPassword" name="frmForgotPassword">		
		<div class="controls">
			<div class="main_input_box"> <span class="add-on bg_lo"><i class="icon-envelope"></i></span>
				<input name="your_email_address" type="text" id="your_email_address" placeholder="E-mail address" value="<?php echo $_POST['your_email_address'];?>" class="input2 required email" />
			</div>
		</div>
		<div class="form-actions"> <span class="pull-left"><a href="index.php" class="flip-link btn btn-success" id="to-login">&laquo; Back to login</a></span> <span class="pull-right">
			<input name="btnSend" id="btnSend" type="submit" value="Reecover" class="btn btn-info" />
			<!--<a class="btn btn-info"/>Reecover</a>--></span> </div>
	</form>
	<?php if(empty($msg) == false){ ?>
	<div align="center"><?php echo $msg;?></div>
	<?php } ?>
</div>
<?php include('admin-footer.php');?>
</body>
</html>
